PREDICTION OF CO2 EMISSIONS FROM COUNTRY-SPECIFIC DATA

![images.png]()

Data source


The used data comes from the Climate Change Data of the World Bank Group, which provides country-
specific data on parameters such as CO2 emissions, energy use, population count, urban population, cereal
yield, nationally terrestrial protected areas, GDP, GNI, etc.


The dataset is publicly available at https://datacatalog.worldbank.org/dataset/climate-change-data and
licenced under the Creative Commons Attribution 4.0 International license.

IMPORT ALL NEEDED LIBRARIES:-

In [ ]:
import pandas as pd
import numpy as np

The complete Climate Change Dataset is imported into a pandas DataFrame from the downloaded file "climate_change_download_0.xls":

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving climate_change_download_0 (1).xls to climate_change_download_0 (1).xls

In [ ]:
# Step 2: Load and check the sheet names
import pandas as pd

file_path = 'climate_change_download_0 (1).xls'

# Check available sheet names
xls = pd.ExcelFile(file_path)
print("Sheet names:", xls.sheet_names)

Sheet names: ['Data', 'Country', 'Series']

In [ ]:
# Step 3: Read the data from the correct sheet
data_sheet = xls.sheet_names[0]  # Automatically pick the first sheet
data_orig = pd.read_excel(file_path, sheet_name=data_sheet)

# Show first 5 rows
data_orig.head()

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

GLOBAL DATA OVERVIEW:-

A global overview of the imported data yields the following insights

In [ ]:
print("Shape of the original dataset:")
data_orig.shape

Shape of the original dataset:

(13512, 28)

In [ ]:
print("Available columns:")
data_orig.columns

Available columns:

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [ ]:
print("Column data types:")
data_orig.dtypes

Column data types:

Country code    object
Country name    object
Series code     object
Series name     object
SCALE           object
Decimals        object
1990            object
1991            object
1992            object
1993            object
1994            object
1995            object
1996            object
1997            object
1998            object
1999            object
2000            object
2001            object
2002            object
2003            object
2004            object
2005            object
2006            object
2007            object
2008            object
2009            object
2010            object
2011            object
dtype: object

In [ ]:
print("Overview of the first 5 rows:")
data_orig.head()

Overview of the first 5 rows:

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [ ]:
print("Descriptive statistics of the columns:")
data_orig.describe()

Descriptive statistics of the columns:

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
count,13512,13512,13512,13512,13512,13512,10017,10017,10017,10017,...,10017,10017,10017,10017,10017,10017,10017,10017,10017,12382
unique,233,233,58,58,2,3,4355,3398,3523,3583,...,3877,3869,4007,4484,4008,4047,4080,3506,2164,1434
top,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
freq,58,58,233,233,10017,5823,5163,6520,6364,6300,...,5960,5974,5792,4933,5781,5769,5414,6256,7685,10244

In order to better understand the nature of the columns "Series code", "Series name', "SCALE" and "Decimals", it is necessary to examine their values.

The following snippet prints the contents of the column *'Series name'*:

In [ ]:
data_orig['Series name'].unique()

array(['Land area below 5m (% of land area)',
       'Agricultural land under irrigation (% of total ag. land)',
       'Cereal yield (kg per hectare)',
       'Foreign direct investment, net inflows (% of GDP)',
       'Access to electricity (% of total population)',
       'Energy use per units of GDP (kg oil eq./$1,000 of 2005 PPP $)',
       'Energy use per capita (kilograms of oil equivalent)',
       'CO2 emissions, total (KtCO2)',
       'CO2 emissions per capita (metric tons)',
       'CO2 emissions per units of GDP (kg/$1,000 of 2005 PPP $)',
       'Other GHG emissions, total (KtCO2e)',
       'Methane (CH4) emissions, total (KtCO2e)',
       'Nitrous oxide (N2O) emissions, total (KtCO2e)',
       'Annex-I emissions reduction target',
       'Disaster risk reduction progress score (1-5 scale; 5=best)',
       'GHG net emissions/removals by LUCF (MtCO2e)',
       'Hosted Clean Development Mechanism (CDM) projects',
       'Hosted Joint Implementation (JI) projects',
       'Average annual precipitation (1961-1990, mm)',
       'Issued Certified Emission Reductions (CERs) from CDM (thousands)',
       'Issued Emission Reduction Units (ERUs) from JI (thousands)',
       'Droughts, floods, extreme temps (% pop. avg. 1990-2009)',
       'Average daily min/max temperature (1961-1990, Celsius)',
       'NAMA submission', 'NAPA submission',
       'Latest UNFCCC national communication',
       'Projected annual temperature change (2045-2065, Celsius)',
       'Projected change in annual cool days/cold nights',
       'Projected change in annual hot days/warm nights',
       'Projected annual precipitation change (2045-2065, mm)',
       'Renewable energy target', 'Population below 5m (% of total)',
       'Population in urban agglomerations >1million (%)',
       'Annual freshwater withdrawals (% of internal resources)',
       'Nationally terrestrial protected areas (% of total land area)',
       'Ease of doing business (ranking 1-183; 1=best)',
       'Invest. in energy w/ private participation ($)',
       'Invest. in telecoms w/ private participation ($)',
       'Invest. in transport w/ private participation ($)',
       'Invest. in water/sanit. w/ private participation ($)',
       'Public sector mgmt & institutions avg. (1-6 scale; 6=best)',
       'Paved roads (% of total roads)', 'GDP ($)',
       'GNI per capita (Atlas $)',
       'Ratio of girls to boys in primary & secondary school (%)',
       'Primary completion rate, total (% of relevant age group)',
       'Under-five mortality rate (per 1,000)',
       'Access to improved water source (% of total pop.)',
       'Nurses and midwives (per 1,000 people)',
       'Physicians (per 1,000 people)',
       'Malaria incidence rate (per 100,000 people)',
       'Access to improved sanitation (% of total pop.)',
       'Child malnutrition, underweight (% of under age 5)',
       'Population living below $1.25 a day (% of total)',
       'Population growth (annual %)', 'Population',
       'Urban population growth (annual %)', 'Urban population'],
      dtype=object)

Contents of the column *'Series code'*:

In [ ]:
data_orig['Series code'].unique()

array(['AG.LND.EL5M.ZS', 'AG.LND.IRIG.AG.ZS', 'AG.YLD.CREL.KG',
       'BX.KLT.DINV.WD.GD.ZS', 'EG.ELC.ACCS.ZS', 'EG.USE.COMM.GD.PP.KD',
       'EG.USE.PCAP.KG.OE', 'EN.ATM.CO2E.KT', 'EN.ATM.CO2E.PC',
       'EN.ATM.CO2E.PP.GD.KD', 'EN.ATM.GHGO.KT.CE', 'EN.ATM.METH.KT.CE',
       'EN.ATM.NOXE.KT.CE', 'EN.CLC.AERT', 'EN.CLC.DRSK.XQ',
       'EN.CLC.GHGR.MT.CE', 'EN.CLC.HCDM', 'EN.CLC.HJIP',
       'EN.CLC.HPPT.MM', 'EN.CLC.ICER', 'EN.CLC.IERU', 'EN.CLC.MDAT.ZS',
       'EN.CLC.MMDT.C', 'EN.CLC.NAMA', 'EN.CLC.NAPA', 'EN.CLC.NCOM',
       'EN.CLC.PCAT.C', 'EN.CLC.PCCC', 'EN.CLC.PCHW', 'EN.CLC.PCPT.MM',
       'EN.CLC.RNET', 'EN.POP.EL5M.ZS', 'EN.URB.MCTY.TL.ZS',
       'ER.H2O.FWTL.ZS', 'ER.LND.PTLD.ZS', 'IC.BUS.EASE.XQ',
       'IE.PPI.ENGY.CD', 'IE.PPI.TELE.CD', 'IE.PPI.TRAN.CD',
       'IE.PPI.WATR.CD', 'IQ.CPA.PUBS.XQ', 'IS.ROD.PAVE.ZS',
       'NY.GDP.MKTP.CD', 'NY.GNP.PCAP.CD', 'SE.ENR.PRSC.FM.ZS',
       'SE.PRM.CMPT.ZS', 'SH.DYN.MORT', 'SH.H2O.SAFE.ZS',
       'SH.MED.NUMW.P3', 'SH.MED.PHYS.ZS', 'SH.MLR.INCD', 'SH.STA.ACSN',
       'SH.STA.MALN.ZS', 'SI.POV.DDAY', 'SP.POP.GROW', 'SP.POP.TOTL',
       'SP.URB.GROW', 'SP.URB.TOTL'], dtype=object)

Contents of the column *'SCALE'*:

In [ ]:
data_orig['SCALE'].unique()

array([0, 'Text'], dtype=object)

Contents of the column *'Decimals'*:

In [ ]:
data_orig['Decimals'].unique()

array([1, 0, 'Text'], dtype=object)

At this point, it is unclear what are the values marked with the label *'Text'* in the *'SCALE'* and *'Decimals'* columns. These are shown in the following tow outputs:

In [ ]:
data_orig[data_orig['SCALE']=='Text']

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
3029,ABW,Aruba,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3030,ADO,Andorra,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3031,AFG,Afghanistan,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3032,AGO,Angola,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3033,ALB,Albania,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7218,YEM,"Yemen, Rep.",EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7219,ZAF,South Africa,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
7220,ZAR,"Congo, Dem. Rep.",EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7221,ZMB,Zambia,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7222,ZWE,Zimbabwe,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..

In [ ]:
data_orig[data_orig['Decimals']=='Text']

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
3029,ABW,Aruba,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3030,ADO,Andorra,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3031,AFG,Afghanistan,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3032,AGO,Angola,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3033,ALB,Albania,EN.CLC.AERT,Annex-I emissions reduction target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7218,YEM,"Yemen, Rep.",EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7219,ZAF,South Africa,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
7220,ZAR,"Congo, Dem. Rep.",EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7221,ZMB,Zambia,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..
7222,ZWE,Zimbabwe,EN.CLC.RNET,Renewable energy target,Text,Text,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,..

### Findings from the global overview

This global overview gives away the following facts about the available data:
* shape: 28 columns, 13512 rows
* all columns are of type "object" - neither numeric, nor string/text values
* A certain amount of missing values, denoted both as NaN (not a number values) and as the string ".."
* The rows marked as *'Text'* in the columns *'SCALE'* and *'Decimals'* do not contain any information, almost completely composed of NaN values
* The columns represent key values such as country, but also the corresponding years and the series code/name
* The columns *'Country name'*, *'Series code'*, *'SCALE'* and *'Decimals'* do not give any information and are therefore obsolete
* The column *'Series name'* contains the country-specific features required for the analysis
* The names of the features in the column *'Series name'* are clear but too long

### Project Goals

This machine learning project begins with a high-level analysis of the dataset to define initial goals, which will evolve as deeper insights emerge. Early goal-setting guides data cleaning, transformation, and visualization.

The dataset includes country-level features across:

- Greenhouse gas emissions (CO₂, CH₄, N₂O, etc.)
- Demographics (population size, urbanization, growth)
- Economy (GDP, GNI, FDI)
- Land use (cereal yield, protected areas)
- Climate data (precipitation, disasters)
- Energy consumption
- Health infrastructure
- Others

**Initial Objective:**  
To analyze the relationships between these features and their impact on climate indicators like emissions and precipitation. Ultimately, the goal is to develop an ML model to predict climate-related variables using country-specific parameters.

These goals will be refined as the project progresses.

### Data Cleaning

#### Organization of the data cleaning and transformation


The main goal is to restructure the dataset by converting the country parameters (from the *'Series name'* column) into individual features, with each row representing a unique country-year pair. Years will be consolidated into a single column for clarity.

Additional steps include removing empty rows/columns and handling missing values to ensure data quality and consistency.

For these purposes, the following tasks have to be undertaken:

1. Remove rows marked as "Text" in the "SCALE" and "Decimals" columns
2. Remove the unnecessary columns "Country name", "Series code", "SCALE", "Decimals"
3. Transform the ".." strings and emplty cells ("") into NaN values for easier recognission as missing values
4. Transform all data columns into a numerical data type
5. Rename the features in column "Series name"

#### Removing rows marked as "Text" in the "SCALE" and "Decimals" columns

In [ ]:
# assign the data to a new DataFrame, which will be modified
data_clean = data_orig

print("Original number of rows:")
print(data_clean.shape[0])

# remove rows characterized as "Text" in the SCALE column
data_clean = data_clean[data_clean['SCALE']!='Text']

print("Current number of rows:")
print(data_clean.shape[0])

Original number of rows:
13512
Current number of rows:
10017

#### Removing the unnecessary columns "Country name", "Series code", "SCALE", "Decimals"

In [ ]:
print("Original number of columns:")
print(data_clean.shape[1])

data_clean = data_clean.drop(['Country name', 'Series code', 'SCALE', 'Decimals'], axis='columns')

print("Current number of columns:")
print(data_clean.shape[1])

Original number of columns:
28
Current number of columns:
24

#### Transform the ".." strings and emplty cells ("") into NaN values for easier recognission as missing values

In [ ]:
data_clean.iloc[:,2:] = data_clean.iloc[:,2:].replace({'':np.nan, '..':np.nan})

/tmp/ipython-input-39-1081394343.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_clean.iloc[:,2:] = data_clean.iloc[:,2:].replace({'':np.nan, '..':np.nan})

#### Transform all data columns into a numerical data type

In [ ]:
data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))
# Errors are ignored in order to avoid error messages about the first two columns, which don't need to be transformed
# into numeric type anyway

print("Print the column data types after transformation:")
data_clean2.dtypes

/tmp/ipython-input-41-266892086.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))
/tmp/ipython-input-41-266892086.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))

Print the column data types after transformation:

Country code    object
Country name    object
Series code     object
Series name     object
SCALE            int64
Decimals         int64
1990            object
1991            object
1992            object
1993            object
1994            object
1995            object
1996            object
1997            object
1998            object
1999            object
2000            object
2001            object
2002            object
2003            object
2004            object
2005            object
2006            object
2007            object
2008            object
2009            object
2010            object
2011            object
dtype: object

#### Rename the features in column "Series name"

The variable/feature names in the column *'Series name'* are clear, but too long and not practical to use in the code. In order to improve that, the most relevant feature names will be renamed with shorter labels as indicated in the following table:

<table>
    <tr>
        <td> <b>Variable name</b> </td>
        <td> <b>Description</b> </td>
        <td> <b>Unit</b> </td>
    </tr>
    <tr>
        <td> cereal_yield </td>
        <td> Cereal yield </td>
        <td> kg per hectare </td>
    </tr>
    <tr>
        <td> fdi_perc_gdp </td>
        <td> Foreign direct investment, net inflows </td>
        <td> % of GDP </td>
    </tr>
    <tr>
        <td> elec_access_perc </td>
        <td> Access to electricity </td>
        <td> % of total population </td>
    </tr>
    <tr>
        <td> en_per_gdp </td>
        <td> Energy use per units of GDP </td>
        <td> kg oil eq./\$1,000 of 2005 PPP \$ </td>
    </tr>
    <tr>
        <td> en_per_cap </td>
        <td> Energy use per capita </td>
        <td> kilograms of oil equivalent </td>
    </tr>
    <tr>
        <td> co2_ttl </td>
        <td> CO2 emissions, total </td>
        <td> KtCO2 </td>
    </tr>
    <tr>
        <td> co2_per_cap </td>
        <td> CO2 emissions, total </td>
        <td> metric tons </td>
    </tr>
    <tr>
        <td> co2_per_gdp </td>
        <td> CO2 emissions per units of GDP </td>
        <td> kg/\$1,000 of 2005 PPP \$ </td>
    </tr>
    <tr>
        <td> other_ghg_ttl </td>
        <td> Other GHG emissions, total </td>
        <td> KtCO2e </td>
    </tr>
    <tr>
        <td> ch4_ttl </td>
        <td> Methane (CH4) emissions, total </td>
        <td> KtCO2 </td>
    </tr>
    <tr>
        <td> n2o_ttl </td>
        <td> Nitrous oxide (N2O) emissions, total </td>
        <td> KtCO2 </td>
    </tr>
    <tr>
        <td> nat_emerg </td>
        <td> Droughts, floods, extreme temps </td>
        <td> % pop. avg. 1990-2009 </td>
    </tr>
    <tr>
        <td> pop_urb_aggl_perc </td>
        <td> Population in urban agglomerations >1million </td>
        <td> % </td>
    </tr>
    <tr>
        <td> prot_area_perc </td>
        <td> Nationally terrestrial protected areas </td>
        <td> % of total land area </td>
    </tr>
    <tr>
        <td> gdp </td>
        <td> Gross Domestic Product (GDP) </td>
        <td> \$ </td>
    </tr>
    <tr>
        <td> gni_per_cap </td>
        <td> GNI per capita </td>
        <td> Atlas \$ </td>
    </tr>
    <tr>
        <td> under_5_mort_rate </td>
        <td> Under-five mortality rate </td>
        <td> per 1,000 </td>
    </tr>
    <tr>
        <td> pop_growth_perc </td>
        <td> Population growth </td>
        <td> annual % </td>
    </tr>
    <tr>
        <td> pop </td>
        <td> Population </td>
        <td> 1 </td>
    </tr>
    <tr>
        <td> urb_pop_growth_perc </td>
        <td> Urban population growth </td>
        <td> annual % </td>
    </tr>
    <tr>
        <td> urb_pop </td>
        <td> Urban population </td>
        <td> 1 </td>
    </tr>
    
</table>

In [ ]:
# define shorter names corresponding to most relevant variables in a dictionary
chosen_vars = {'Cereal yield (kg per hectare)': 'cereal_yield',
               'Foreign direct investment, net inflows (% of GDP)': 'fdi_perc_gdp',
               'Access to electricity (% of total population)': 'elec_access_perc',
               'Energy use per units of GDP (kg oil eq./$1,000 of 2005 PPP $)': 'en_per_gdp',
               'Energy use per capita (kilograms of oil equivalent)': 'en_per_cap',
               'CO2 emissions, total (KtCO2)': 'co2_ttl',
               'CO2 emissions per capita (metric tons)': 'co2_per_cap',
               'CO2 emissions per units of GDP (kg/$1,000 of 2005 PPP $)': 'co2_per_gdp',
               'Other GHG emissions, total (KtCO2e)': 'other_ghg_ttl',
               'Methane (CH4) emissions, total (KtCO2e)': 'ch4_ttl',
               'Nitrous oxide (N2O) emissions, total (KtCO2e)': 'n2o_ttl',
               'Droughts, floods, extreme temps (% pop. avg. 1990-2009)': 'nat_emerg',
               'Population in urban agglomerations >1million (%)': 'pop_urb_aggl_perc',
               'Nationally terrestrial protected areas (% of total land area)': 'prot_area_perc',
               'GDP ($)': 'gdp',
               'GNI per capita (Atlas $)': 'gni_per_cap',
               'Under-five mortality rate (per 1,000)': 'under_5_mort_rate',
               'Population growth (annual %)': 'pop_growth_perc',
               'Population': 'pop',
               'Urban population growth (annual %)': 'urb_pop_growth_perc',
               'Urban population': 'urb_pop'
                }

# rename all variables in the column "Series name" with comprehensible shorter versions
data_clean2['Series name'] = data_clean2['Series name'].replace(to_replace=chosen_vars)

***

### Data frame transformation

This is how the current data frame looks like:

In [ ]:
data_clean2.head()

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

To prepare the data for analysis, the values in the *'Series name'* column are pivoted into separate feature columns, while years are combined into a single column. This involves melting the dataset to align values with their corresponding country and year, and then merging them into a unified, structured DataFrame.

In [ ]:
# save the short feature names into a list of strings
chosen_cols = list(chosen_vars.values())

# define an empty list, where sub-dataframes for each feature will be saved
frame_list = []

# iterate over all chosen features
for variable in chosen_cols:

    # pick only rows corresponding to the current feature
    frame = data_clean2[data_clean2['Series name'] == variable]

    # melt all the values for all years into one column and rename the columns correspondingly
    frame = frame.melt(id_vars=['Country code', 'Series name']).rename(columns={'Country code': 'country', 'variable': 'year', 'value': variable}).drop(['Series name'], axis='columns')

    # add the melted dataframe for the current feature into the list
    frame_list.append(frame)


# merge all sub-frames into a single dataframe, making an outer binding on the key columns 'country','year'
from functools import reduce
all_vars = reduce(lambda left, right: pd.merge(left, right, on=['country','year'], how='outer'), frame_list)

After this transformation, the new data frame has the following layout:

In [ ]:
all_vars.head()

,country,year,cereal_yield,fdi_perc_gdp,elec_access_perc,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,...,nat_emerg,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop
0,ABW,1990,..,..,..,..,..,1840.834,29.620641,..,...,..,..,0.105547,..,..,..,1.820254,62147,1.780501,31259.941
1,ABW,1991,..,21.185138,..,..,..,1928.842,29.838835,..,...,..,..,0.10493,872067021.913829,..,..,3.936181,64642,3.337974,32321
2,ABW,1992,..,-3.857809,..,..,..,1723.49,25.239288,..,...,..,..,0.10493,958659238.282076,..,..,5.484041,68286,4.882234,33938.142
3,ABW,1993,..,-1.655492,..,..,..,1771.161,24.405233,..,...,..,..,0.10493,1083240282.27456,14940,..,6.088818,72573,5.483368,35851.062
4,ABW,1994,..,-5.874439,..,..,..,1763.827,22.977867,..,...,..,..,0.10493,1245810153.89127,15320,..,5.611677,76762,5.002538,37690.142

***

### Remove the remaining missing values in an optimal way

Although some columns and rows with empty cells have already been deleted, there are still remaining missing values:

In [ ]:
print("check the amount of missing values in each column")
all_vars.isnull().sum()

check the amount of missing values in each column

country                 0
year                    0
cereal_yield            0
fdi_perc_gdp            0
elec_access_perc        0
en_per_gdp              0
en_per_cap              0
co2_ttl                 0
co2_per_cap             0
co2_per_gdp             0
other_ghg_ttl           0
ch4_ttl                 0
n2o_ttl                 0
nat_emerg               0
pop_urb_aggl_perc       0
prot_area_perc          0
gdp                     0
gni_per_cap             0
under_5_mort_rate       0
pop_growth_perc        26
pop                     0
urb_pop_growth_perc    26
urb_pop                 0
dtype: int64

### Handling Missing Values

The goal is to minimize missing data while retaining as much useful information as possible. Instead of dropping all rows with NaNs, the approach filters by year, country, and feature—removing rows or columns starting with those that have the most missing values.

Since countries and years appear multiple times, NaN counts are aggregated per unique country and year to guide selective cleaning.

#### Filtering the years by missing values

Checking the amount of missing values for each year:

In [ ]:
all_vars_clean = all_vars

#define an array with the unique year values
years_count_missing = dict.fromkeys(all_vars_clean['year'].unique(), 0)
for ind, row in all_vars_clean.iterrows():
    years_count_missing[row['year']] += row.isnull().sum()

# sort the years by missing values
years_missing_sorted = dict(sorted(years_count_missing.items(), key=lambda item: item[1]))

# print the missing values for each year
print("missing values by year:")
for key, val in years_missing_sorted.items():
    print(key, ":", val)

missing values by year:
1990 : 2
1991 : 2
1992 : 2
1993 : 2
1994 : 2
1995 : 2
1996 : 2
1997 : 2
1998 : 2
1999 : 2
2000 : 2
2001 : 2
2002 : 2
2003 : 2
2004 : 2
2005 : 2
2006 : 2
2007 : 2
2008 : 2
2009 : 2
2010 : 2
2011 : 2
Country name : 2
Decimals : 2
SCALE : 2
Series code : 2

### Filtering by Year

The goal is to remove countries with excessive missing data while preserving the time span as much as possible. To achieve this, a threshold for allowed NaN values per year is applied.

Based on earlier analysis, the years 1991 to 2008 offer a good balance and are selected for further processing.

In [ ]:
# Step 1: Drop rows with missing values (optional, depends on your data)
data_clean = data_orig.dropna()

# Step 2: Convert applicable cells to numeric, ignoring errors for string columns
data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))

# Step 3: Print data types of columns after transformation
print("Column data types after transformation:")
print(data_clean2.dtypes)

/tmp/ipython-input-50-4271777267.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))
/tmp/ipython-input-50-4271777267.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data_clean2 = data_clean.applymap(lambda x: pd.to_numeric(x, errors='ignore'))

Column data types after transformation:
Country code    object
Country name    object
Series code     object
Series name     object
SCALE            int64
Decimals         int64
1990            object
1991            object
1992            object
1993            object
1994            object
1995            object
1996            object
1997            object
1998            object
1999            object
2000            object
2001            object
2002            object
2003            object
2004            object
2005            object
2006            object
2007            object
2008            object
2009            object
2010            object
2011            object
dtype: object

In [ ]:
# Upload the file
from google.colab import files
uploaded = files.upload()

Saving climate_change_download_0 (1).xls to climate_change_download_0 (1) (1).xls

In [ ]:
# Read Excel file
import pandas as pd
file_path = 'climate_change_download_0 (1).xls'

xls = pd.ExcelFile(file_path)
print("Sheet names:", xls.sheet_names)

data_sheet = xls.sheet_names[0]
data_orig = pd.read_excel(file_path, sheet_name=data_sheet)

Sheet names: ['Data', 'Country', 'Series']

#### Filtering the countries by missing values

The same procedure is applied to the filtering of countries with missing values. The following snippet shows the number of NaNs for each country.

In [ ]:
# check the amount of missing values by country

# define an array with the unique country values
countries_count_missing = dict.fromkeys(all_vars_clean['country'].unique(), 0)

# iterate through all rows and count the amount of NaN values for each country
for ind, row in all_vars_clean.iterrows():
    countries_count_missing[row['country']] += row.isnull().sum()

# sort the countries by missing values
countries_missing_sorted = dict(sorted(countries_count_missing.items(), key=lambda item: item[1]))

# print the missing values for each country
print("missing values by country:")
for key, val in countries_missing_sorted.items():
    print(key, ":", val)

missing values by country:
ABW : 0
ADO : 0
AFG : 0
AGO : 0
ALB : 0
ARE : 0
ARG : 0
ARM : 0
ASM : 0
ATG : 0
AUS : 0
AUT : 0
AZE : 0
BDI : 0
BEL : 0
BEN : 0
BFA : 0
BGD : 0
BGR : 0
BHR : 0
BHS : 0
BIH : 0
BLR : 0
BLZ : 0
BMU : 0
BOL : 0
BRA : 0
BRB : 0
BRN : 0
BTN : 0
BWA : 0
CAF : 0
CAN : 0
CHE : 0
CHI : 0
CHL : 0
CHN : 0
CIV : 0
CMR : 0
COG : 0
COK : 0
COL : 0
COM : 0
CPV : 0
CRI : 0
CUB : 0
CUW : 0
CYM : 0
CYP : 0
CZE : 0
DEU : 0
DJI : 0
DMA : 0
DNK : 0
DOM : 0
DZA : 0
EAP : 0
ECA : 0
ECU : 0
EGY : 0
EMU : 0
ERI : 0
ESP : 0
EST : 0
ETH : 0
FIN : 0
FJI : 0
FRA : 0
FRO : 0
FSM : 0
GAB : 0
GBR : 0
GEO : 0
GHA : 0
GIB : 0
GIN : 0
GMB : 0
GNB : 0
GNQ : 0
GRC : 0
GRD : 0
GRL : 0
GTM : 0
GUM : 0
GUY : 0
HIC : 0
HKG : 0
HND : 0
HRV : 0
HTI : 0
HUN : 0
IDN : 0
IMY : 0
IND : 0
IRL : 0
IRN : 0
IRQ : 0
ISL : 0
ISR : 0
ITA : 0
JAM : 0
JOR : 0
JPN : 0
KAZ : 0
KEN : 0
KGZ : 0
KHM : 0
KIR : 0
KNA : 0
KOR : 0
KSV : 0
KWT : 0
LAC : 0
LAO : 0
LBN : 0
LBR : 0
LBY : 0
LCA : 0
LIC : 0
LIE : 0
LKA : 0
LMC : 0
LMY : 0
LSO : 0
LTU : 0
LUX : 0
LVA : 0
MAC : 0
MAF : 0
MAR : 0
MCO : 0
MDA : 0
MDG : 0
MDV : 0
MEX : 0
MHL : 0
MIC : 0
MKD : 0
MLI : 0
MLT : 0
MMR : 0
MNA : 0
MNE : 0
MNG : 0
MNP : 0
MOZ : 0
MRT : 0
MUS : 0
MWI : 0
MYS : 0
MYT : 0
NAM : 0
NCL : 0
NER : 0
NGA : 0
NIC : 0
NIU : 0
NLD : 0
NOR : 0
NPL : 0
NRU : 0
NZL : 0
OMN : 0
PAK : 0
PAN : 0
PER : 0
PHL : 0
PLW : 0
PNG : 0
POL : 0
PRI : 0
PRK : 0
PRT : 0
PRY : 0
PYF : 0
QAT : 0
ROM : 0
RUS : 0
RWA : 0
SAS : 0
SAU : 0
SDN : 0
SEN : 0
SGP : 0
SLB : 0
SLE : 0
SLV : 0
SMR : 0
SOM : 0
SRB : 0
SSA : 0
STP : 0
SUR : 0
SVK : 0
SVN : 0
SWE : 0
SWZ : 0
SXM : 0
SYC : 0
SYR : 0
TCA : 0
TCD : 0
TGO : 0
THA : 0
TJK : 0
TKM : 0
TMP : 0
TON : 0
TTO : 0
TUN : 0
TUR : 0
TUV : 0
TZA : 0
UGA : 0
UKR : 0
UMC : 0
URY : 0
USA : 0
UZB : 0
VCT : 0
VEN : 0
VIR : 0
VNM : 0
VUT : 0
WBG : 0
WLD : 0
WSM : 0
YEM : 0
ZAF : 0
ZAR : 0
ZMB : 0
ZWE : 0
SID : 52

This output would suggest to remove rows for countries with more than 90 missing values:

In [ ]:
print("number of missing values in the whole dataset before filtering the countries:")
print(all_vars_clean.isnull().sum().sum())
print("number of rows before filtering the countries:")
print(all_vars_clean.shape[0])


# filter only rows for countries with less than 90 missing values
countries_filter = []
for key, val in countries_missing_sorted.items():
    if val<90:
        countries_filter.append(key)

all_vars_clean = all_vars_clean[all_vars_clean['country'].isin(countries_filter)]

print("number of missing values in the whole dataset after filtering the countries:")
print(all_vars_clean.isnull().sum().sum())
print("number of rows after filtering the countries:")
print(all_vars_clean.shape[0])

number of missing values in the whole dataset before filtering the countries:
52
number of rows before filtering the countries:
6058
number of missing values in the whole dataset after filtering the countries:
52
number of rows after filtering the countries:
6058

#### Checking the features (columns) for missing values

The NaN values count in each column is:

In [ ]:
all_vars_clean.isnull().sum()

country                 0
year                    0
cereal_yield            0
fdi_perc_gdp            0
elec_access_perc        0
en_per_gdp              0
en_per_cap              0
co2_ttl                 0
co2_per_cap             0
co2_per_gdp             0
other_ghg_ttl           0
ch4_ttl                 0
n2o_ttl                 0
nat_emerg               0
pop_urb_aggl_perc       0
prot_area_perc          0
gdp                     0
gni_per_cap             0
under_5_mort_rate       0
pop_growth_perc        26
pop                     0
urb_pop_growth_perc    26
urb_pop                 0
dtype: int64

### Dropping High-NaN Features

Even after filtering countries and years, some features like *elec_access_perc*, *other_ghg_ttl*, *ch4_ttl*, *n20_ttl*, and *nat_emerg* still have many missing values. Keeping them would significantly reduce the dataset size, so these columns are dropped to preserve more complete observations.

In [ ]:
# remove features with more than 20 missing values

from itertools import compress

# create a boolean mapping of features with more than 20 missing values
vars_bad = all_vars_clean.isnull().sum()>20

# remove the columns corresponding to the mapping of the features with many missing values
all_vars_clean2 = all_vars_clean.drop(compress(data = all_vars_clean.columns, selectors = vars_bad), axis='columns')

print("Remaining missing values per column:")
print(all_vars_clean2.isnull().sum())

Remaining missing values per column:
country              0
year                 0
cereal_yield         0
fdi_perc_gdp         0
elec_access_perc     0
en_per_gdp           0
en_per_cap           0
co2_ttl              0
co2_per_cap          0
co2_per_gdp          0
other_ghg_ttl        0
ch4_ttl              0
n2o_ttl              0
nat_emerg            0
pop_urb_aggl_perc    0
prot_area_perc       0
gdp                  0
gni_per_cap          0
under_5_mort_rate    0
pop                  0
urb_pop              0
dtype: int64

Removing the rows with the remainin missing values will not impair the size of the dataset significantly, so these rows will be deleted:

In [ ]:
# delete rows with any number of missing values
all_vars_clean3 = all_vars_clean2.dropna(axis='rows', how='any')

print("Remaining missing values per column:")
print(all_vars_clean3.isnull().sum())

print("Final shape of the cleaned dataset:")
print(all_vars_clean3.shape)

Remaining missing values per column:
country              0
year                 0
cereal_yield         0
fdi_perc_gdp         0
elec_access_perc     0
en_per_gdp           0
en_per_cap           0
co2_ttl              0
co2_per_cap          0
co2_per_gdp          0
other_ghg_ttl        0
ch4_ttl              0
n2o_ttl              0
nat_emerg            0
pop_urb_aggl_perc    0
prot_area_perc       0
gdp                  0
gni_per_cap          0
under_5_mort_rate    0
pop                  0
urb_pop              0
dtype: int64
Final shape of the cleaned dataset:
(6058, 21)

***

### Export of the cleaned data frame to a file

Now that the dataset has been rearranged and cleaned of missing values, it can be exported to a csv file (without the row index) for further analysis:

In [ ]:
from google.colab import files
files.download('data_cleaned.csv')

The further stages of the project are Data Visualization and Predictive Analysis, which can be found in the corresponding notebooks.

***